# -*- coding: utf-8 -*-
"""numpy(arrays)_yt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j8AWDXFySPoEz3BZ37URDilFVF0KFMmY

**Basic Array Creation**
"""

import numpy as np

arr=np.array([1,2,3,4,5])
arr

a=[1,2,3,4,"hello"]
a

np.array(a)

l=[[1,2,3],[4,5,6],[7,8,9]]
l

np.array(l)

"""**Array generational functions**"""

arr=np.arange(1,11,2)
arr

arr=np.zeros((6,6))
arr

arr=np.ones((6))
arr

arr=np.linspace(1,5,2)
arr

"""**Random Generation Function**"""

np.random.rand(5)

np.random.randint(10,20,10)

"""**Array Attributes**"""

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

arr.shape

arr.dtype

"""**Array Methods**"""

arr

arr.min()

arr.max()

arr.sum()

np.sum(arr,axis=0)

arr.mean()

arr.std()

arr.argmax()

arr.argmin()

"""**Array Reshaping And Resizing**"""

arr=np.arange(1,31)
arr=arr.reshape(6,5)

arr



